#!/bin/bash

echo "🔑 Hướng dẫn thêm OPENAI_API_KEY vào .env trên VPS:"
echo ""
echo "📝 Trên VPS, chạy lệnh sau:"
echo ""
echo "nano .env"
echo ""
echo "Sau đó thêm dòng này vào cuối file:"
echo ""
echo "OPENAI_API_KEY=sk-your-actual-api-key-here"
echo ""
echo "---"
echo ""
echo "Hoặc nếu bạn muốn thêm tự động (thay YOUR_KEY bằng key thật):"
echo ""
echo "echo 'OPENAI_API_KEY=sk-YOUR_KEY' >> .env"
echo ""
echo "---"
echo ""
echo "Sau đó kiểm tra lại:"
echo ""
echo "cat .env | grep OPENAI_API_KEY"

