#!/bin/bash

echo "🔧 Fix PM2 port conflict trên VPS:"
echo ""
echo "📝 Trên VPS, chạy các lệnh sau:"
echo ""
echo "1. Stop và xóa tất cả processes:"
echo "   pm2 stop all"
echo "   pm2 delete all"
echo ""
echo "2. Kiểm tra port 3000 đang được sử dụng bởi process nào:"
echo "   lsof -i :3000"
echo "   hoặc"
echo "   netstat -tulpn | grep 3000"
echo ""
echo "3. Nếu có process khác đang dùng port 3000, kill nó:"
echo "   kill -9 <PID>"
echo ""
echo "4. Khởi động lại với PM2:"
echo "   pm2 start ecosystem.config.js"
echo ""
echo "5. Kiểm tra lại:"
echo "   pm2 status"
echo "   pm2 logs ctss"

