#!/bin/bash

echo "🔧 Quick Fix Nginx - Chạy script này trên VPS:"
echo ""
echo "cd ~/ctss"
echo ""
echo "# 1. Fix PM2"
echo "pm2 stop all"
echo "pm2 delete all"
echo "fuser -k 3000/tcp 2>/dev/null || pkill -f 'next start' || true"
echo "pm2 start ecosystem.config.js"
echo "pm2 save"
echo "sleep 5"
echo ""
echo "# 2. Kiểm tra PM2"
echo "pm2 status"
echo "curl http://localhost:3000"
echo ""
echo "# 3. Fix Nginx config"
echo "rm -f /etc/nginx/sites-enabled/ctss"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "cp nginx-ctss.conf /etc/nginx/sites-available/ctss"
echo "ln -s /etc/nginx/sites-available/ctss /etc/nginx/sites-enabled/ctss"
echo "nginx -t"
echo "systemctl restart nginx"
echo ""
echo "# 4. Kiểm tra"
echo "curl http://localhost"
echo "pm2 logs ctss --lines 20"

