import {
  LayoutDashboard,
  Calendar,
  Users,
  Scissors,
  Package,
  UserCircle,
  ShoppingCart,
  BarChart3,
  Settings,
  Sparkles,
  CheckCircle,
  Phone,
  Award,
  Heart,
  Building2,
  Target,
  TrendingUp,
  DollarSign,
} from "lucide-react";
import { CTSSRole } from "@/features/auth/types";

// Unified menu item structure
export interface MenuItemData {
  key: string;
  label: string;
  path: string;
  group: string;
  icon: any;
  roles: CTSSRole[];
  children?: MenuItemData[];
}

// Menu items data source - Single source of truth
export const MENU_ITEMS: MenuItemData[] = [
  {
    key: "dashboard-main",
    label: "Main Dashboard",
    path: "/dashboard",
    group: "Dashboard",
    icon: LayoutDashboard,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST", "STYLIST", "ASSISTANT"],
  },
  {
    key: "insights",
    label: "Operation Insights",
    path: "/dashboard/insights",
    group: "Dashboard",
    icon: BarChart3,
    roles: ["OWNER", "ADMIN"], // Phase 10.1: Only OWNER/ADMIN
  },
  {
    key: "actions",
    label: "AI Actions",
    path: "/dashboard/actions",
    group: "Dashboard",
    icon: Sparkles,
    roles: ["OWNER", "ADMIN"], // Phase 11.3: Only OWNER/ADMIN
  },
  {
    key: "automation",
    label: "Automation",
    path: "/dashboard/automation",
    group: "Dashboard",
    icon: Settings,
    roles: ["OWNER"], // Phase 12: Only OWNER
  },
  {
    key: "dashboard-ceo",
    label: "CEO Control Tower",
    path: "/control-tower",
    group: "Dashboard",
    icon: LayoutDashboard,
    roles: ["ADMIN"],
  },
  {
    key: "booking-calendar",
    label: "Booking Calendar",
    path: "/booking",
    group: "Đặt lịch",
    icon: Calendar,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST", "STYLIST", "ASSISTANT"],
  },
  {
    key: "crm-dashboard",
    label: "CRM Dashboard",
    path: "/crm",
    group: "Khách hàng",
    icon: Users,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST", "STYLIST"],
  },
  {
    key: "membership",
    label: "Membership",
    path: "/membership",
    group: "Khách hàng",
    icon: Award,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "personalization",
    label: "Personalization",
    path: "/personalization",
    group: "Khách hàng",
    icon: Target,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "services",
    label: "Services",
    path: "/services",
    group: "Dịch vụ",
    icon: Scissors,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST", "STYLIST", "ASSISTANT"],
  },
  {
    key: "pricing",
    label: "Pricing",
    path: "/pricing",
    group: "Dịch vụ",
    icon: DollarSign,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "inventory",
    label: "Inventory",
    path: "/inventory",
    group: "Kho hàng",
    icon: Package,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST"],
  },
  {
    key: "staff",
    label: "Staff",
    path: "/staff",
    group: "Nhân viên",
    icon: UserCircle,
    roles: ["STYLIST", "ASSISTANT"],
  },
  {
    key: "staff-management",
    label: "Staff Management",
    path: "/staff-management",
    group: "Nhân viên",
    icon: UserCircle,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "pos",
    label: "POS",
    path: "/pos",
    group: "Bán hàng",
    icon: ShoppingCart,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST"],
  },
  {
    key: "sales-dashboard",
    label: "Sales Dashboard",
    path: "/sales",
    group: "Bán hàng",
    icon: TrendingUp,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "reports",
    label: "Reports",
    path: "/reports",
    group: "Báo cáo",
    icon: BarChart3,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "reports-financial",
    label: "Financial",
    path: "/reports/financial",
    group: "Báo cáo",
    icon: DollarSign,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "marketing-dashboard",
    label: "Marketing Dashboard",
    path: "/marketing/dashboard",
    group: "Marketing",
    icon: Sparkles,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "quality",
    label: "Quality",
    path: "/quality",
    group: "Analytics",
    icon: CheckCircle,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "voice-analytics",
    label: "Voice Analytics",
    path: "/voice",
    group: "Analytics",
    icon: Phone,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "hair-health",
    label: "Hair Health",
    path: "/hair-health",
    group: "Analytics",
    icon: Heart,
    roles: ["ADMIN", "MANAGER", "STYLIST"],
  },
  {
    key: "operations",
    label: "Operations",
    path: "/operations",
    group: "Hệ thống",
    icon: Settings,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "training",
    label: "Training",
    path: "/training/dashboard",
    group: "Hệ thống",
    icon: Settings,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "sop",
    label: "SOP",
    path: "/sop",
    group: "Hệ thống",
    icon: Settings,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "workflow",
    label: "Workflow",
    path: "/workflow-console",
    group: "Hệ thống",
    icon: Settings,
    roles: ["ADMIN", "MANAGER"],
  },
  {
    key: "partner-hq",
    label: "Partner HQ",
    path: "/partner/hq",
    group: "Hệ thống",
    icon: Building2,
    roles: ["ADMIN"],
  },
  {
    key: "salons",
    label: "Quản lý Salon",
    path: "/system/salons",
    group: "Hệ thống",
    icon: Building2,
    roles: ["ADMIN"],
  },
  {
    key: "subscription",
    label: "Gói Dịch vụ",
    path: "/system/subscription",
    group: "Hệ thống",
    icon: Building2,
    roles: ["OWNER"], // Phase 8: Only OWNER can manage subscription
  },
  {
    key: "settings",
    label: "Settings",
    path: "/settings",
    group: "Hệ thống",
    icon: Settings,
    roles: ["ADMIN"],
  },
  {
    key: "mina-ai",
    label: "Mina AI",
    path: "/mina",
    group: "AI",
    icon: Sparkles,
    roles: ["ADMIN", "MANAGER", "RECEPTIONIST", "STYLIST", "ASSISTANT"],
  },
];

// Group order for business logic
export const GROUP_ORDER: string[] = [
  "Dashboard",
  "Đặt lịch",
  "Khách hàng",
  "Dịch vụ",
  "Kho hàng",
  "Nhân viên",
  "Bán hàng",
  "Báo cáo",
  "Marketing",
  "Analytics",
  "Hệ thống",
  "AI",
];

// Group icons mapping
export const GROUP_ICONS: Record<string, any> = {
  Dashboard: LayoutDashboard,
  "Đặt lịch": Calendar,
  "Khách hàng": Users,
  "Dịch vụ": Scissors,
  "Kho hàng": Package,
  "Nhân viên": UserCircle,
  "Bán hàng": ShoppingCart,
  "Báo cáo": BarChart3,
  Marketing: Sparkles,
  Analytics: BarChart3,
  "Hệ thống": Settings,
  AI: Sparkles,
};

